(function addConcurrencyTrack() {
  const q = (level, question, answer) => ({ level, question, answer });
  const card = (title, body) => ({ title, body });
  const lesson = (spec) => ({
    level: "ADV",
    concepts: [],
    examples: [],
    flow: [],
    tradeoffs: [],
    failures: [],
    useWhen: [],
    avoidWhen: [],
    questions: [],
    ...spec
  });
  const topic = (id, week, day, title, goal, subtopics) => ({ id, week, day, title, goal, subtopics });
  const cards = (items) => items.map(([title, body]) => card(title, body));
  const qs = (items) => items.map(([level, question, answer]) => q(level, question, answer));
  const day = (n, id, title, spec) => lesson({
    id: `day-${String(n).padStart(2, "0")}-${id}`,
    name: `Day ${n}: ${title}`,
    problem: spec.problem,
    mentalModel: spec.mental,
    core: spec.core,
    deepDive: spec.deep,
    concepts: cards(spec.concepts),
    examples: cards(spec.examples),
    flow: spec.flow,
    tradeoffs: cards(spec.tradeoffs),
    failures: spec.failures,
    useWhen: spec.useWhen,
    avoidWhen: spec.avoidWhen,
    codeTitle: spec.codeTitle || `${title} Java sketch`,
    code: spec.code,
    questions: qs(spec.questions),
    revision: spec.revision
  });

  const phase1 = topic("p1-os-jvm-bridge", 9, 1, "Phase 1: OS to JVM Bridge", "Days 1-6: understand how the machine schedules execution and manages memory before writing concurrent Java code.", [
    day(1, "processes-vs-threads", "Processes vs Threads", {
      problem: "A Java concurrency answer is weak if you cannot explain what the OS is scheduling. Processes isolate memory; threads share a process address space and compete for CPU time.",
      mental: "A process is the running application boundary. A thread is an execution path inside that boundary. PCB owns process-level facts; TCB owns per-thread execution facts.",
      core: "PCB stores process id, address-space metadata, open files, security context, and scheduling state. TCB stores program counter, registers, stack pointer, thread state, and scheduling information.",
      deep: "A modern Java platform thread maps to a native OS thread. Threads in one JVM process share heap, metaspace, code cache, and file descriptors, but each thread has its own call stack and register state. This is why two threads can mutate the same object but cannot share the same local stack frame.",
      concepts: [["Process", "Isolated address space plus OS-owned resources."], ["Thread", "A schedulable execution stream inside a process."], ["PCB vs TCB", "PCB is process bookkeeping; TCB is thread execution bookkeeping."], ["Java mapping", "A normal Java platform thread maps to one native kernel thread on modern HotSpot."]],
      examples: [["Browser", "A browser may isolate tabs/processes while each tab uses many threads."], ["Java server", "One JVM process has request, GC, JIT, and scheduler threads."], ["Redis-Lite", "Request workers and the TTL daemon share the same cache map in one JVM process."]],
      flow: ["Program starts", "OS creates process and PCB", "JVM starts", "JVM creates threads", "OS schedules TCBs onto CPU cores"],
      tradeoffs: [["Process isolation", "Safer but heavier."], ["Thread sharing", "Fast communication but races become possible."], ["Interview choice", "Use threads for shared in-memory cache work; use processes for isolation."]],
      failures: ["Saying threads have separate heaps.", "Ignoring local stack vs shared heap.", "Assuming more threads always means more CPU progress."],
      useWhen: ["Explaining Java server execution.", "Reasoning about shared heap data structures."],
      avoidWhen: ["Do not discuss PCB/TCB deeply unless concurrency is relevant."],
      code: "Thread worker = new Thread(() -> cache.put(\"user:1\", \"A\"));\nworker.start();\n\n// Thread object is Java-level metadata; execution is backed by JVM/OS scheduling.",
      questions: [["EASY", "Process vs thread?", "A process owns an isolated address space; threads share a process address space but each has its own stack."], ["MEDIUM", "What does TCB store?", "Program counter, registers, stack pointer, state, and scheduling metadata."], ["HARD", "Why does this matter for Redis-Lite?", "The map is shared heap state, so request threads and daemon threads can race unless protected."]],
      revision: "Process = isolation boundary. Thread = schedulable path sharing process memory."
    }),
    day(2, "context-switching", "Context Switching Cost", {
      problem: "Creating many threads looks easy, but the CPU pays when it switches among them. Too many runnable platform threads waste cycles and hurt tail latency.",
      mental: "A context switch is the CPU saving one thread bookmark and loading another. The hidden cost is lost cache warmth.",
      core: "Context switching saves/restores registers, program counter, and stack pointer, then resumes a different execution path. The new thread may cause L1/L2 cache misses.",
      deep: "The cost is not only kernel bookkeeping. After switching, the new thread often touches different memory, causing cold cache lines and branch predictor misses. A tiny cache get can become slower if the system is drowning in thread switches.",
      concepts: [["Runnable vs running", "Many threads can be ready; only core-count threads run at once."], ["Direct cost", "Scheduler saves/restores execution state."], ["Indirect cost", "Cache locality is lost."], ["Latency", "Switching increases tail latency under load."]],
      examples: [["Web server", "Too many request threads increase switching and queueing."], ["GC pause", "Application threads stop and resume, creating spikes."], ["Redis-Lite", "Do not create a new thread for every get or put."]],
      flow: ["Thread A runs", "Timer/block occurs", "Kernel saves A", "Scheduler picks B", "Kernel restores B", "CPU warms new data"],
      tradeoffs: [["More threads", "Helps blocking workloads but increases switching."], ["Fewer threads", "Less overhead but may underuse resources."], ["Bounded pool", "Predictable default for a cache/server."]],
      failures: ["Using new Thread for every cache request.", "Confusing concurrency with parallelism.", "Ignoring blocked threads while sizing pools."],
      useWhen: ["Sizing executors.", "Explaining why thread pools exist."],
      avoidWhen: ["Do not micro-optimize switching before fixing blocking and lock contention."],
      code: "ExecutorService pool = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors());\npool.submit(() -> cache.get(\"k1\"));",
      questions: [["EASY", "What is context switching?", "The CPU switches execution from one thread/process to another by saving and restoring state."], ["MEDIUM", "Why can it hurt cache performance?", "The resumed thread may need different memory, causing cache misses."], ["HARD", "How reduce context switch pressure?", "Use bounded executors, avoid blocking inside locks, and separate CPU-bound from IO-bound work."]],
      revision: "Context switching = scheduling overhead plus cache locality loss."
    }),
    day(3, "user-kernel-java-threads", "User-Space Threads, Kernel Threads, and Java Mapping", {
      problem: "Executor sizing is guesswork if you do not know whether Java threads consume OS resources.",
      mental: "Kernel threads are scheduled by the OS. User-space threads are scheduled by a runtime. Java platform threads are OS-backed; virtual threads are JVM-managed over carrier threads.",
      core: "Classic Java Thread uses a native OS thread. Virtual threads reduce blocking-thread cost but do not remove CPU limits or shared-state races.",
      deep: "In interviews, say platform threads map one-to-one with OS threads. If mentioning virtual threads, be precise: they help blocking-style code scale, but a ConcurrentHashMap plus LRU metadata still needs synchronization.",
      concepts: [["Kernel thread", "Known and scheduled by the OS."], ["User-space thread", "Known to the runtime and cheaper to manage."], ["Platform thread", "Traditional Java thread backed by native thread."], ["Virtual thread", "Lightweight Java thread scheduled over carrier threads."]],
      examples: [["Tomcat classic", "Bounded platform-thread request pool."], ["Virtual-thread service", "Many blocking requests with fewer OS threads."], ["Redis-Lite", "Use ordinary executors first; discuss virtual threads only for request wrappers."]],
      flow: ["Java creates task", "JVM maps execution", "OS schedules carrier/platform thread", "Thread touches shared heap", "Synchronization protects correctness"],
      tradeoffs: [["Platform threads", "Predictable but expensive at huge counts."], ["Virtual threads", "Great for blocking IO, not a CPU multiplier."], ["Interview scope", "Use platform-thread model unless asked about Java 21+."]],
      failures: ["Saying Java always uses green threads today.", "Using virtual threads to justify unsafe mutation.", "Forgetting CPU-bound work is limited by cores."],
      useWhen: ["Discussing thread pools and resource limits."],
      avoidWhen: ["Do not add virtual threads to a simple LLD unless they solve a real bottleneck."],
      code: "try (var executor = Executors.newVirtualThreadPerTaskExecutor()) {\n    executor.submit(() -> cache.get(\"key\"));\n}\n// Shared cache metadata still needs locks.",
      questions: [["EASY", "How do platform threads map?", "Usually one Java platform thread maps to one native OS thread."], ["MEDIUM", "What do virtual threads improve?", "They reduce the cost of many blocking tasks."], ["HARD", "Do virtual threads solve races?", "No. Shared mutable state still needs synchronization."]],
      revision: "Thread implementation can change; shared heap correctness does not."
    }),
    day(4, "virtual-memory-paging", "Virtual Memory, Paging, and Page Faults", {
      problem: "The JVM does not receive a flat physical memory array. The OS gives virtual memory, maps pages to frames, and handles misses through page faults.",
      mental: "Virtual memory is an address translation layer. JVM sees virtual addresses; OS/MMU map pages to physical RAM.",
      core: "Paging splits memory into fixed pages. A page fault occurs when a referenced page is missing or violates permissions.",
      deep: "For Java, page faults matter when heap grows, memory is swapped, or large allocations touch fresh pages. A low-latency cache must avoid memory pressure because major page faults destroy latency.",
      concepts: [["Virtual address", "Address seen by process/JVM."], ["Page table", "Virtual page to physical frame mapping."], ["Page fault", "Trap into OS for missing/invalid mapping."], ["Swap risk", "Disk-backed paging is disastrous for cache latency."]],
      examples: [["JVM heap", "Reserved/committed virtual memory backed by pages."], ["Large cache", "Can pressure RAM and trigger reclaim."], ["Container", "Memory limits can cause OOM or heavy paging." ]],
      flow: ["Thread reads address", "MMU checks translation", "TLB/page table checked", "Fault if missing", "OS maps/loads page", "Thread resumes slowly"],
      tradeoffs: [["Virtual memory", "Isolation and flexible allocation."], ["Large heap", "More cache capacity but more GC/page pressure."], ["Capacity limit", "Keep Redis-Lite below available RAM." ]],
      failures: ["Designing unlimited cache capacity.", "Ignoring entry memory overhead.", "Treating page faults as Java exceptions."],
      useWhen: ["Sizing an in-memory store."],
      avoidWhen: ["Do not go deep into MMU unless memory/latency is central."],
      code: "long maxEntries = 1_000_000;\nCache<String, byte[]> cache = new RedisLiteCache<>(maxEntries);\n// Capacity is a memory safety feature.",
      questions: [["EASY", "What is virtual memory?", "A per-process address space translated to physical memory."], ["MEDIUM", "What is a page fault?", "A trap when a page is missing or invalid."], ["HARD", "Why do page faults matter for a cache?", "They can turn memory-speed access into millisecond stalls."]],
      revision: "Virtual memory gives isolation; paging mistakes kill latency."
    }),
    day(5, "stack-heap", "OS Stack vs Heap Allocation", {
      problem: "Java memory explanations fail when stack frames, object heap, references, and shared state are mixed together.",
      mental: "A method call creates a thread-private stack frame. Objects usually live on the shared heap. A local variable may hold a reference to a shared heap object.",
      core: "Each thread has its own stack. The Java heap is shared by all threads in the JVM process.",
      deep: "The JVM may keep locals in registers, stack slots, or optimize them away. The interview model remains: local frame is private; heap object is shared if reachable by many threads.",
      concepts: [["Thread stack", "Per-thread call frames and locals."], ["Heap", "Shared dynamic allocation area."], ["Reference", "Local pointer to heap object."], ["Escape analysis", "JVM can optimize non-escaping allocations." ]],
      examples: [["Local counter", "int count inside method is thread-local."], ["Shared map", "ConcurrentHashMap field is shared heap."], ["LRU node", "Local reference may point to shared node." ]],
      flow: ["Method called", "Stack frame created", "Objects allocated if needed", "Frame popped on return", "Reachable heap object remains"],
      tradeoffs: [["Stack", "Fast and thread-confined."], ["Heap", "Flexible sharing, needs GC/synchronization."], ["Immutable object", "Safe sharing after construction." ]],
      failures: ["Believing local reference means local object.", "Sharing mutable objects without synchronization.", "Ignoring stack overflow from recursion."],
      useWhen: ["Explaining visibility and shared state."],
      avoidWhen: ["Do not expose internal heap objects directly from cache API."],
      code: "class CacheService {\n    private final ConcurrentHashMap<String, Entry> store = new ConcurrentHashMap<>();\n    Entry get(String key) {\n        Entry localRef = store.get(key);\n        return localRef;\n    }\n}",
      questions: [["EASY", "Do threads share stacks?", "No. Each thread has its own stack."], ["MEDIUM", "Can a local variable lead to shared mutation?", "Yes, if it references a shared heap object."], ["HARD", "Why important for Redis-Lite?", "Map, entries, and LRU nodes live on shared heap and need safe access." ]],
      revision: "Stack is per-thread; heap is shared; references connect them."
    }),
    day(6, "jmm-visibility-gc", "JMM, Visibility, and GC Latency", {
      problem: "A thread may update a field while another keeps reading an old value. GC can also pause all application threads and break latency expectations.",
      mental: "The JMM defines when writes become visible. GC finds dead objects but may stop the world during parts of collection.",
      core: "Visibility requires happens-before through volatile, synchronized, locks, thread start/join, or concurrent utilities. Mark-and-sweep marks reachable objects and reclaims the rest. Stop-the-world pauses hurt tail latency.",
      deep: "Locals may live in registers or L1 cache; fields may be read from cache; JVM can reorder unless JMM forbids it. For Redis-Lite, volatile is useful for daemon flags, locks protect compound metadata, and TTL cleanup reduces GC pressure.",
      concepts: [["Happens-before", "Visibility and ordering guarantee."], ["Visibility", "One thread observes another write."], ["Mark-and-sweep", "Marks live objects and reclaims dead ones."], ["Stop-the-world", "Application threads pause during GC phases." ]],
      examples: [["Shutdown flag", "volatile running flag."], ["Cache entry publication", "CHM/locks safely publish entries."], ["Expired keys", "Too many dead entries increase GC pressure." ]],
      flow: ["Thread A writes", "No happens-before may hide write", "volatile/lock creates barrier", "Thread B reads fresh value", "GC later marks and sweeps"],
      tradeoffs: [["volatile", "Good visibility for simple flags."], ["Locks", "Visibility plus atomicity."], ["GC tuning", "Useful after lifecycle design is sane." ]],
      failures: ["Using volatile for count++.", "Ignoring GC in TTL design.", "Returning mutable internal objects."],
      useWhen: ["Daemon stop flags.", "Explaining cache latency."],
      avoidWhen: ["Do not use volatile as universal locking."],
      code: "final class TtlDaemon implements Runnable {\n    private volatile boolean running = true;\n    public void stop() { running = false; }\n    public void run() { while (running) sweepExpiredKeys(); }\n}",
      questions: [["EASY", "What does volatile solve?", "Visibility and ordering for that variable."], ["MEDIUM", "Why not volatile for count++?", "count++ is read-add-write and needs atomicity."], ["HARD", "Why can GC kill latency?", "Stop-the-world phases pause application threads." ]],
      revision: "JMM controls visibility; GC controls cleanup but can pause execution."
    })
  ]);

  const phase2 = topic("p2-sync-lock-free", 10, 7, "Phase 2: Synchronization and Lock-Free Primitives", "Days 7-13: master visibility, CAS, atomics, monitors, and explicit locks without destroying throughput.", [    day(7, "mesi", "MESI and CPU Cache Coherence", {
      problem: "CPU cores have private caches. If two cores cache the same memory location, hardware needs coherence so they do not permanently disagree.",
      mental: "MESI is traffic control for cache lines: Modified, Exclusive, Shared, Invalid.",
      core: "Cache coherence coordinates ownership and invalidation of cache lines. Java volatile and locks create correct visibility on top of hardware behavior.",
      deep: "MESI does not make Java operations atomic. It can keep cache lines coherent, but if two threads read count=5 and both write 6, the protocol cannot know the intended result was 7.",
      concepts: [["Cache line", "Unit moved between memory and CPU caches."], ["Modified", "This core owns the newest changed line."], ["Shared", "Multiple cores can read the line."], ["Invalidation", "Other cached copies are marked stale after a write." ]],
      examples: [["AtomicInteger", "CAS cooperates with cache coherence."], ["False sharing", "Different hot variables on one cache line bounce between cores."], ["Redis-Lite metrics", "Hot hit counters can become contention points." ]],
      flow: ["Core A reads line", "Core B reads same line", "Core A writes", "Protocol invalidates B copy", "B reloads before fresh read"],
      tradeoffs: [["Coherence", "Makes shared-memory machines usable."], ["Hot cache line", "Heavy writes cause bouncing."], ["Design fix", "Avoid unnecessary shared writes on read path." ]],
      failures: ["Assuming MESI removes locks.", "Updating global metrics on every get without thinking.", "Ignoring false sharing."],
      useWhen: ["Explaining volatile and atomics."],
      avoidWhen: ["Do not over-explain MESI unless performance is central."],
      code: "AtomicLong hits = new AtomicLong();\nlong recordHit() { return hits.incrementAndGet(); }",
      questions: [["EASY", "What does cache coherence solve?", "It keeps cores from permanently disagreeing about cached memory values."], ["MEDIUM", "Does MESI make count++ atomic?", "No. It is coherence, not program-level atomicity."], ["HARD", "How can coherence hurt throughput?", "Hot writes make cache lines bounce across cores." ]],
      revision: "MESI keeps cache lines coherent; synchronization defines correctness."
    }),
    day(8, "volatile", "volatile Keyword", {
      problem: "A background thread may never see a normal boolean flag change if there is no happens-before edge.",
      mental: "volatile is a visibility and ordering tool, not a mutual exclusion tool.",
      core: "A write to a volatile variable happens-before every later read of that same variable. It is ideal for simple flags and immutable reference publication.",
      deep: "Do not say volatile literally flushes the whole CPU cache. Say it creates JMM ordering/visibility constraints. It cannot protect map plus LRU list together.",
      concepts: [["Visibility", "Reader observes latest volatile write."], ["Ordering", "JVM/CPU cannot reorder in ways that break JMM rules."], ["No compound atomicity", "volatile count++ still loses updates."], ["Publication", "Can publish immutable references with care." ]],
      examples: [["Daemon flag", "volatile running stops sweeper."], ["Config pointer", "volatile immutable config reference."], ["Bad counter", "volatile hits++ is unsafe." ]],
      flow: ["Writer updates state", "Writer writes volatile", "Reader reads volatile", "Reader sees prior writes"],
      tradeoffs: [["Cheap visibility", "Usually lighter than lock."], ["Limited", "No multi-field invariant."], ["Best fit", "Lifecycle flags and immutable swaps." ]],
      failures: ["Using volatile for check-then-act.", "Mutating object internals after volatile publication.", "Overusing volatile where a lock is clearer."],
      useWhen: ["Simple flags.", "One-writer config publication."],
      avoidWhen: ["Multi-field invariants and read-modify-write."],
      code: "private volatile boolean running = true;\nvoid shutdown() { running = false; }\nwhile (running) { sweepOnce(); }",
      questions: [["EASY", "What does volatile guarantee?", "Visibility and ordering for that variable."], ["MEDIUM", "Why is volatile count++ unsafe?", "It is read, add, write; volatile does not make all three atomic."], ["HARD", "Where use volatile in Redis-Lite?", "Daemon running flags or immutable config reference swaps." ]],
      revision: "volatile is visibility, not a lock."
    }),
    day(9, "cas", "Compare-And-Swap", {
      problem: "Locks can block. CAS updates a value only if it still equals the expected old value.",
      mental: "CAS says: I saw A; change to B only if nobody changed A since I looked.",
      core: "CAS is a CPU-supported atomic primitive used by Java atomic classes. It avoids blocking but can spin under contention.",
      deep: "CAS is optimistic. It shines when conflicts are rare. Under high contention, many threads fail and retry, burning CPU. Use CAS for counters/references, not complex linked LRU invariants first.",
      concepts: [["Expected value", "What the thread believes is current."], ["New value", "Value to install on success."], ["Retry loop", "Reread after failure."], ["Lock-free", "System makes progress even if some threads retry." ]],
      examples: [["AtomicInteger", "CAS-based increment."], ["AtomicReference", "Swap immutable config."], ["Cache stats", "Hit/miss counters." ]],
      flow: ["Read current", "Compute next", "CAS expected to next", "Success returns", "Failure retries"],
      tradeoffs: [["No blocking", "Avoids parking threads."], ["Spinning", "Can waste CPU."], ["Single variable", "Great; linked structures are harder." ]],
      failures: ["Infinite CAS loops under contention.", "CAS across multiple objects without plan.", "Ignoring ABA."],
      useWhen: ["Counters and single-reference updates."],
      avoidWhen: ["Complex multi-node invariants."],
      code: "AtomicInteger size = new AtomicInteger();\nint oldValue;\ndo {\n    oldValue = size.get();\n} while (!size.compareAndSet(oldValue, oldValue + 1));",
      questions: [["EASY", "What are CAS inputs?", "Expected old value and desired new value."], ["MEDIUM", "Why can CAS beat locks?", "It avoids blocking when contention is low."], ["HARD", "When is CAS worse?", "High contention or multi-object invariants can cause retries and complexity." ]],
      revision: "CAS is optimistic atomic update."
    }),
    day(10, "atomic-classes", "Java Atomic Classes", {
      problem: "You need safe counters and reference swaps without writing synchronized blocks everywhere.",
      mental: "Atomic classes wrap volatile visibility plus CAS update methods behind a small API.",
      core: "AtomicInteger and AtomicLong are good for counters. AtomicReference is good for swapping immutable references atomically.",
      deep: "Atomic classes make one variable safe, not a whole structure. Hit count is independent; LRU head/tail/links are not independent.",
      concepts: [["AtomicInteger", "CAS-based int operations."], ["AtomicLong", "CAS-based long counters."], ["AtomicReference", "CAS-based reference swap."], ["Independence rule", "Use atomics when one variable owns the invariant." ]],
      examples: [["Cache stats", "hits.incrementAndGet()."], ["Config reload", "AtomicReference<Config>."], ["Bad LRU", "Multiple independent atomics cannot easily protect pointer consistency." ]],
      flow: ["Choose atomic variable", "Keep invariant local", "Use built-in update", "Avoid unlocked compound state"],
      tradeoffs: [["Low ceremony", "Less code than locks for simple values."], ["Limited scope", "No cross-variable consistency."], ["LongAdder", "Better for very hot approximate counters." ]],
      failures: ["Multiple atomics treated as one transaction.", "Returning mutable config.", "Atomic size while map/list update fails."],
      useWhen: ["Independent counters and immutable reference publication."],
      avoidWhen: ["Linked list or map plus policy invariants."],
      code: "final class CacheMetrics {\n    private final AtomicLong hits = new AtomicLong();\n    void hit() { hits.incrementAndGet(); }\n}",
      questions: [["EASY", "Which atomic stores object references?", "AtomicReference."], ["MEDIUM", "What invariant should atomics protect?", "One independent variable or immutable reference swap."], ["HARD", "Why not LRU only from atomics?", "LRU changes several pointers and metadata values together." ]],
      revision: "Atomics are excellent for independent single-variable state."
    }),
    day(11, "aba", "ABA Problem", {
      problem: "CAS can be fooled when a value changes A to B and back to A. Equality hides history.",
      mental: "You checked the chair is in the same place, but missed that it was removed, changed, and put back.",
      core: "Solve ABA with version stamps, AtomicStampedReference, AtomicMarkableReference, or by avoiding raw lock-free node reuse.",
      deep: "ABA appears in lock-free stacks/queues and linked metadata. For Redis-Lite, a lock-based LRU list is easier and safer than a clever lock-free list.",
      concepts: [["A-B-A", "Same final value with important intermediate change."], ["Stamp", "Version changes every update."], ["AtomicStampedReference", "CAS reference plus stamp."], ["Design escape", "Use locks for linked eviction metadata." ]],
      examples: [["Lock-free stack", "Head removed and reused."], ["Object pool", "Same reference has new meaning."], ["LRU node", "Removed/reinserted while another thread observed it." ]],
      flow: ["Thread reads A", "Other thread changes A to B", "Other changes B to A", "First CAS succeeds incorrectly", "Stamped CAS would fail"],
      tradeoffs: [["Stamped reference", "Prevents ABA with complexity."], ["GC", "Reduces some reuse risk, not logical ABA."], ["Locking", "Simpler for interview LLD." ]],
      failures: ["Ignoring ABA in lock-free linked structures.", "Assuming GC removes all ABA risk.", "Overengineering normal map operations."],
      useWhen: ["Explaining lock-free risks."],
      avoidWhen: ["Ordinary ConcurrentHashMap usage."],
      code: "AtomicStampedReference<Node> head = new AtomicStampedReference<>(null, 0);\nint[] stamp = new int[1];\nNode current = head.get(stamp);\nhead.compareAndSet(current, next, stamp[0], stamp[0] + 1);",
      questions: [["EASY", "What is ABA?", "A value changes A to B and back to A, fooling equality-based CAS."], ["MEDIUM", "How does a stamp help?", "A with version 1 differs from A with version 3."], ["HARD", "How handle ABA in Redis-Lite?", "Avoid lock-free LRU first; use a lock around linked metadata." ]],
      revision: "ABA is equality without history; stamps add history."
    }),
    day(12, "synchronized", "synchronized and Monitor Objects", {
      problem: "Some invariants need mutual exclusion. synchronized gives every Java object a monitor lock and visibility edge.",
      mental: "A monitor is a room with one key. One thread enters; leaving publishes writes to the next entrant.",
      core: "synchronized protects critical sections and creates happens-before from unlock to later lock on same monitor.",
      deep: "synchronized is not bad. It is often the clearest answer for a small class. Keep the lock scope small and never call slow external systems while holding it.",
      concepts: [["Monitor", "Every Java object can be a lock."], ["Reentrancy", "Same thread can reacquire."], ["Happens-before", "Unlock publishes to later lock."], ["Critical section", "Small block protecting invariant." ]],
      examples: [["Seat lock", "Check and update status atomically."], ["Cache policy", "Protect list mutation."], ["Bad callback", "Listener inside lock can deadlock." ]],
      flow: ["Acquire monitor", "Check invariant", "Mutate state", "Release monitor", "Next thread sees writes"],
      tradeoffs: [["Simple", "Clear correctness."], ["Coarse", "Can serialize too much."], ["Limited", "No timed/interruptible acquisition." ]],
      failures: ["Locking on public objects.", "Holding lock during IO.", "Assuming synchronized method protects other objects."],
      useWhen: ["Small shared object invariants."],
      avoidWhen: ["Need timeout, fairness, or read/write split."],
      code: "synchronized boolean tryLockSeat() {\n    if (status != SeatStatus.AVAILABLE) return false;\n    status = SeatStatus.LOCKED;\n    return true;\n}",
      questions: [["EASY", "What does synchronized provide?", "Mutual exclusion plus visibility."], ["MEDIUM", "Why keep blocks small?", "Long locks increase contention."], ["HARD", "When use ReentrantLock instead?", "tryLock, timeout, interruptible lock, fairness, or Conditions." ]],
      revision: "synchronized is simple mutual exclusion with visibility."
    }),
    day(13, "advanced-locks", "ReentrantLock, ReadWriteLock, and StampedLock", {
      problem: "A single monitor can be too limiting for read-heavy or cancellation-aware workloads.",
      mental: "ReentrantLock is programmable synchronized. ReadWriteLock separates readers from writers. StampedLock adds optimistic reads.",
      core: "Use ReentrantLock for tryLock/fairness/interruptibility. Use ReadWriteLock for read-heavy workloads. Use StampedLock carefully for optimistic read patterns.",
      deep: "For Redis-Lite, ReadWriteLock is natural: many reads can proceed, while put/evict/TTL sweep take write lock. Exact LRU complicates this because get mutates recency metadata.",
      concepts: [["ReentrantLock", "Manual lock/unlock with options."], ["ReadWriteLock", "Many readers or one writer."], ["StampedLock", "Optimistic read plus validation."], ["Fairness", "Less starvation, often lower throughput." ]],
      examples: [["Cache get", "Read lock if no metadata mutation."], ["Cache put", "Write lock."], ["StampedLock", "Mostly stable config/state." ]],
      flow: ["Choose lock type", "Acquire read/write", "Do smallest safe operation", "Unlock in finally", "Measure contention"],
      tradeoffs: [["ReadWriteLock", "Great if reads are true reads."], ["Fair lock", "Prevents starvation but can slow throughput."], ["StampedLock", "Powerful but easy to misuse." ]],
      failures: ["Forgetting unlock in finally.", "Mutating LRU under read lock.", "Assuming fairness is always faster."],
      useWhen: ["Read-heavy cache and lock control."],
      avoidWhen: ["Every operation mutates heavily."],
      code: "ReadWriteLock rw = new ReentrantReadWriteLock();\nrw.readLock().lock();\ntry { return readEntry(key); } finally { rw.readLock().unlock(); }",
      questions: [["EASY", "What does ReadWriteLock allow?", "Many concurrent readers or one exclusive writer."], ["MEDIUM", "Why use tryLock?", "To fail fast or avoid waiting forever."], ["HARD", "What is the LRU read-lock problem?", "get updates recency, so exact LRU get is a write." ]],
      revision: "Pick lock type based on invariant shape and read/write ratio."
    })
  ]);

  const phase3 = topic("p3-thread-management", 11, 14, "Phase 3: High-Throughput Thread Management", "Days 14-20: manage thousands of tasks with executors, concurrent collections, queues, and waiting mechanics.", [
    day(14, "executor", "Executor Framework", {
      problem: "new Thread().start() per task bypasses pooling, backpressure, naming, monitoring, and lifecycle control.",
      mental: "An executor is a managed work intake system: workers, queue, and rejection policy.",
      core: "ExecutorService separates task submission from thread management and reuses workers.",
      deep: "In Redis-Lite, request execution and TTL sweeps need explicit executors. A cache get should not create a thread; a daemon should be lifecycle-managed.",
      concepts: [["Executor", "Runs tasks using a policy."], ["Worker reuse", "Avoids repeated thread creation."], ["Lifecycle", "shutdown controls stop."], ["Backpressure", "Bounded queues expose overload." ]],
      examples: [["HTTP server", "Request pool."], ["TTL daemon", "Scheduled executor."], ["Metrics", "Separate optional work." ]],
      flow: ["Create executor", "Submit task", "Task queues/runs", "Worker executes", "Shutdown gracefully"],
      tradeoffs: [["Raw thread", "Simple but uncontrolled."], ["Executor", "More setup, better control."], ["Separate pools", "Isolate request and maintenance work." ]],
      failures: ["Thread per request.", "Forgetting shutdown.", "Unbounded pools/queues."],
      useWhen: ["Repeatable async tasks."],
      avoidWhen: ["One tiny throwaway demo."],
      code: "ExecutorService requestPool = Executors.newFixedThreadPool(8);\nrequestPool.submit(() -> cache.put(\"a\", \"1\"));\nrequestPool.shutdown();",
      questions: [["EASY", "Why avoid new Thread per request?", "It creates unbounded OS resources."], ["MEDIUM", "What does ExecutorService separate?", "Task submission from thread management."], ["HARD", "How use it in Redis-Lite?", "Request workers plus ScheduledExecutorService for TTL cleanup." ]],
      revision: "Executors turn raw threads into managed capacity."
    }),
    day(15, "thread-pool-executor", "ThreadPoolExecutor Anatomy", {
      problem: "Factory methods hide important knobs like core size, max size, keep-alive, queue, and rejection handler.",
      mental: "ThreadPoolExecutor is an intake pipeline: core workers, queue, extra workers, then rejection.",
      core: "Core threads handle baseline work, queue buffers tasks, max threads handle pressure depending on queue, keepAlive removes idle extras, rejection handles overload.",
      deep: "With unbounded LinkedBlockingQueue, maxPoolSize is mostly irrelevant because tasks queue instead of creating extra workers. Queue choice changes behavior.",
      concepts: [["corePoolSize", "Baseline workers."], ["maximumPoolSize", "Upper bound."], ["keepAliveTime", "Idle extra worker lifetime."], ["workQueue", "Controls buffering and growth." ]],
      examples: [["CPU pool", "Near available processors."], ["IO pool", "Larger if blocking."], ["Redis-Lite", "Bounded request pool protects latency." ]],
      flow: ["Submit task", "Create core worker if needed", "Else enqueue", "Else grow to max", "Else reject"],
      tradeoffs: [["Large queue", "Smooths bursts but hides latency."], ["Large max", "Can increase switching."], ["Bounded queue", "Exposes overload early." ]],
      failures: ["newFixedThreadPool without knowing unbounded queue.", "Expecting maxPoolSize with unbounded queue.", "Unnamed threads."],
      useWhen: ["Need explicit capacity and rejection."],
      avoidWhen: ["Tiny app where factory is enough."],
      code: "ThreadPoolExecutor pool = new ThreadPoolExecutor(4, 8, 30, TimeUnit.SECONDS, new ArrayBlockingQueue<>(100), new ThreadPoolExecutor.CallerRunsPolicy());",
      questions: [["EASY", "What is corePoolSize?", "Baseline worker count."], ["MEDIUM", "Why can maxPoolSize be ignored?", "Unbounded queues accept tasks instead of forcing growth."], ["HARD", "How size Redis-Lite workers?", "Start near CPU cores, use bounded queues, measure tail latency." ]],
      revision: "ThreadPoolExecutor = workers + queue + growth + rejection."
    }),
    day(16, "starvation-rejection", "Starvation and Rejection Policies", {
      problem: "A pool can be alive but not progressing if workers are blocked or monopolized.",
      mental: "A pool is a limited kitchen. If all cooks wait for food queued behind them, service freezes.",
      core: "Starvation happens when tasks block on tasks in the same pool, long tasks monopolize workers, or queues hide overload. Rejection policies define overload behavior.",
      deep: "CallerRunsPolicy creates backpressure by making the submitter run work. AbortPolicy fails fast. Discard policies are only safe for optional work.",
      concepts: [["Starvation", "Ready work cannot run."], ["AbortPolicy", "Throws exception."], ["CallerRunsPolicy", "Submitter runs task."], ["Backpressure", "Slow producers instead of growing forever." ]],
      examples: [["Nested future", "Task waits for another task in same full pool."], ["TTL sweep", "Should not starve requests."], ["Cache overload", "CallerRuns slows clients." ]],
      flow: ["Workers busy", "Queue fills", "New task arrives", "Policy runs", "Caller slows/fails/drops"],
      tradeoffs: [["Abort", "Clear failure."], ["CallerRuns", "Natural throttling."], ["Discard", "Only for optional telemetry." ]],
      failures: ["Future.get inside same small pool.", "Discarding important writes.", "Sharing request pool with long maintenance."],
      useWhen: ["Designing overload behavior."],
      avoidWhen: ["Do not ignore rejection."],
      code: "new ThreadPoolExecutor(8, 8, 0, TimeUnit.SECONDS, new ArrayBlockingQueue<>(500), new ThreadPoolExecutor.CallerRunsPolicy());",
      questions: [["EASY", "What is starvation?", "Tasks cannot progress because workers are unavailable."], ["MEDIUM", "What does CallerRunsPolicy do?", "Runs rejected task in submitting thread."], ["HARD", "How prevent TTL sweep starvation?", "Use separate scheduled executor or bounded maintenance pool." ]],
      revision: "Overload needs deliberate rejection/backpressure."
    }),    day(17, "concurrent-hash-map", "ConcurrentHashMap", {
      problem: "A global synchronized map serializes too much work. ConcurrentHashMap gives thread-safe key access with much better scalability.",
      mental: "ConcurrentHashMap is the storage index. Eviction metadata is a separate structure that still needs consistency control.",
      core: "ConcurrentHashMap supports thread-safe get/put, weakly consistent iteration, atomic compute methods, and better throughput than Hashtable or synchronizedMap.",
      deep: "CHM does not protect your external LRU list. If put updates map and list, the combined invariant needs a lock.",
      concepts: [["Hashtable", "Old globally synchronized map."], ["synchronizedMap", "Wrapper with one lock."], ["ConcurrentHashMap", "Fine-grained/CAS internal concurrency."], ["compute", "Atomic per-key update." ]],
      examples: [["Storage", "ConcurrentHashMap<K, Entry<V>>."], ["Per-key update", "compute updates one key atomically."], ["LRU", "Needs separate lock." ]],
      flow: ["get locates bin", "read safely", "put locks/CASes small region", "unrelated keys continue"],
      tradeoffs: [["Throughput", "Great for map operations."], ["Weak iteration", "Not perfect snapshot."], ["External invariant", "Map plus list needs extra coordination." ]],
      failures: ["Assuming CHM makes multi-step cache operation atomic.", "Mutating Entry fields unsafely.", "Using iterator for exact eviction."],
      useWhen: ["High-throughput key-value storage."],
      avoidWhen: ["Need one invariant across map plus several structures without locks."],
      code: "ConcurrentHashMap<String, CacheEntry<String>> store = new ConcurrentHashMap<>();\nstore.compute(\"key\", (k, old) -> new CacheEntry<>(\"value\", expiresAt));",
      questions: [["EASY", "Why faster than Hashtable?", "It avoids one global lock for all operations."], ["MEDIUM", "Are iterators strongly consistent?", "No, they are weakly consistent."], ["HARD", "Does CHM protect LRU metadata?", "No. External metadata needs its own synchronization." ]],
      revision: "ConcurrentHashMap solves map concurrency, not every cache invariant."
    }),
    day(18, "copy-on-write", "CopyOnWriteArrayList", {
      problem: "Some lists are read frequently and modified rarely. Locking every iteration is wasteful, but unsafe iteration can break.",
      mental: "Readers get a stable snapshot. Writers copy the array and publish a new version.",
      core: "CopyOnWriteArrayList is thread-safe for read-heavy, write-rare workloads. Writes are expensive in memory and CPU.",
      deep: "Use it for listener lists or config observers. Do not use it for cache entries, LRU order, queues, or frequent mutation.",
      concepts: [["Snapshot iteration", "Iterator sees an array version."], ["Write copy", "Mutation copies backing array."], ["Read optimized", "Reads need little synchronization."], ["Memory cost", "Writes allocate full copies." ]],
      examples: [["Listeners", "Many notifications, rare registration."], ["Config watchers", "Rare add/remove."], ["Bad LRU", "Every get would copy too much." ]],
      flow: ["Reader gets snapshot", "Writer copies array", "Writer mutates copy", "New array published"],
      tradeoffs: [["Safe iteration", "No normal ConcurrentModificationException."], ["Expensive writes", "Bad for frequent mutation."], ["Stale snapshot", "Iterator may not see newest items." ]],
      failures: ["Using it for LRU list.", "Expecting latest iterator view.", "Ignoring memory churn."],
      useWhen: ["Read-mostly listener/config lists."],
      avoidWhen: ["High-write collections."],
      code: "CopyOnWriteArrayList<CacheListener> listeners = new CopyOnWriteArrayList<>();\nfor (CacheListener listener : listeners) listener.onEvict(key);",
      questions: [["EASY", "What is optimized?", "Reads and safe iteration."], ["MEDIUM", "Why are writes expensive?", "Each mutation copies the backing array."], ["HARD", "Where use it in Redis-Lite?", "Eviction listeners or observers, not cache storage/LRU." ]],
      revision: "Copy-on-write is read-fast, write-expensive snapshot safety."
    }),
    day(19, "blocking-queues", "Blocking Queues and Producer-Consumer", {
      problem: "Producers and consumers need safe handoff. Busy-waiting wastes CPU; unsafe lists corrupt state.",
      mental: "A BlockingQueue is a thread-safe waiting room.",
      core: "ArrayBlockingQueue is bounded and array-backed. LinkedBlockingQueue can be optionally bounded but is often accidentally huge. BlockingQueue implements producer-consumer cleanly.",
      deep: "Use bounded queues for request work if building a server wrapper. ScheduledExecutorService is simpler for TTL cleanup. Bounded queues prevent memory blowups.",
      concepts: [["put/take", "Blocking wait for space/items."], ["offer/poll", "Non-blocking or timed variants."], ["ArrayBlockingQueue", "Fixed capacity."], ["LinkedBlockingQueue", "Linked nodes, optional bound." ]],
      examples: [["Request queue", "Clients produce cache commands."], ["Write-behind", "Queue persistence writes."], ["Metrics", "Optional telemetry can drop." ]],
      flow: ["Producer creates task", "offer into queue", "Consumer take waits", "Consumer processes", "Full queue creates backpressure"],
      tradeoffs: [["Array", "Predictable bounded memory."], ["Linked", "Flexible but allocates nodes."], ["Timed offer", "Graceful overload failure." ]],
      failures: ["Unbounded request queue.", "Busy-waiting.", "Ignoring InterruptedException."],
      useWhen: ["Worker handoff and backpressure."],
      avoidWhen: ["Direct method call is enough."],
      code: "BlockingQueue<Runnable> queue = new ArrayBlockingQueue<>(1000);\nboolean accepted = queue.offer(task, 50, TimeUnit.MILLISECONDS);",
      questions: [["EASY", "Which pattern?", "Producer-consumer."], ["MEDIUM", "Why bounded queues?", "They prevent unlimited memory growth and expose overload."], ["HARD", "Array vs Linked?", "Array is fixed/predictable; linked can allocate many nodes if unbounded." ]],
      revision: "BlockingQueue is safe handoff plus waiting/backpressure."
    }),
    day(20, "wait-notify-condition", "wait/notify and Condition Variables", {
      problem: "Sometimes a thread must wait until a state predicate becomes true. Sleeping is a guess, not synchronization.",
      mental: "wait releases a lock and parks. Condition is the explicit-lock version with named wait sets.",
      core: "wait/notify must be inside synchronized and always use a while loop. Condition works with Lock and supports multiple condition queues.",
      deep: "Prefer higher-level utilities in production. But understanding wait/notify explains BlockingQueue and Conditions under the hood.",
      concepts: [["wait", "Releases monitor and waits."], ["notify", "Wakes waiter but lock must be reacquired."], ["Spurious wakeup", "Wake without predicate true."], ["Condition", "Explicit wait set tied to Lock." ]],
      examples: [["Bounded buffer", "Producer waits while full."], ["Cache warmup", "Requests wait until load complete."], ["Shutdown", "Worker waits for tasks or stop." ]],
      flow: ["Acquire lock", "while condition false wait", "Producer changes state", "Signal", "Waiter rechecks"],
      tradeoffs: [["wait/notify", "Low-level and easy to misuse."], ["Condition", "Clearer for multiple wait reasons."], ["BlockingQueue", "Best producer-consumer default." ]],
      failures: ["Using if instead of while.", "Calling wait without monitor.", "Using notify for multiple conditions."],
      useWhen: ["Learning internals or custom primitive."],
      avoidWhen: ["java.util.concurrent already solves it."],
      code: "lock.lock();\ntry {\n    while (queue.isEmpty()) notEmpty.await();\n    return queue.removeFirst();\n} finally { lock.unlock(); }",
      questions: [["EASY", "Why while around wait?", "Spurious wakeups and races after notification."], ["MEDIUM", "What does wait release?", "The object monitor."], ["HARD", "When prefer Condition?", "With explicit Lock or multiple named wait sets." ]],
      revision: "Wait on predicates, not time guesses."
    })
  ]);

  const phase4 = topic("p4-redis-lite-capstone", 12, 21, "Phase 4: Capstone LLD - Redis-Lite", "Days 21-30: synthesize OS, JVM, concurrency, and LLD principles into a thread-safe in-memory data store.", [
    day(21, "spec-solid", "Redis-Lite Spec and SOLID", {
      problem: "A capstone fails when it starts with ConcurrentHashMap and no product boundary.",
      mental: "Redis-Lite is a small in-memory data store: API, storage, eviction, expiry, concurrency, metrics, lifecycle.",
      core: "Define get, put, delete, contains, expire, size, and shutdown. Keep storage, eviction, expiry, and daemon lifecycle separate.",
      deep: "SOLID matters because eviction can change, time must be fakeable in tests, and concurrency control can evolve. Cache API should not know list pointer details.",
      concepts: [["SRP", "Storage stores; policy evicts; daemon cleans."], ["OCP", "Add LFU without rewriting service."], ["DIP", "Depend on EvictionPolicy and Clock."], ["Invariant", "Capacity and no stale returns." ]],
      examples: [["API", "put/get/delete/expire."], ["Policy", "LRU today, LFU tomorrow."], ["Testing", "FakeClock for TTL." ]],
      flow: ["Clarify API", "Name invariants", "Split responsibilities", "Choose storage", "Add eviction/TTL", "Define shutdown"],
      tradeoffs: [["Small API", "Easy to implement/test."], ["Redis breadth", "More commands, less depth."], ["Best scope", "Key-value with TTL and one eviction strategy." ]],
      failures: ["Implementing all Redis types.", "Putting daemon logic inside get.", "Hardcoding LRU in CacheService."],
      useWhen: ["Beginning capstone design."],
      avoidWhen: ["Do not add networking before in-memory correctness."],
      code: "interface Cache<K,V> extends AutoCloseable {\n    Optional<V> get(K key);\n    void put(K key, V value, Duration ttl);\n    boolean delete(K key);\n    int size();\n}",
      questions: [["EASY", "Core API?", "get, put, delete, expire/TTL, size, shutdown."], ["MEDIUM", "Where does SOLID appear?", "Separate storage, eviction, TTL, clock, daemon."], ["HARD", "Out of scope first?", "Networking, clustering, persistence, Redis protocol, multiple data types." ]],
      revision: "Start Redis-Lite with API and invariants."
    }),
    day(22, "strategy-singleton", "Strategy Pattern and Cache Manager", {
      problem: "Eviction changes by requirement. Cache manager lifecycle must not hide untestable global state.",
      mental: "Strategy handles algorithm variation; Singleton is optional and must stay thin.",
      core: "Use EvictionPolicy<K> for LRU/LFU/FIFO. Prefer injection; use Singleton only for one process-wide manager if required.",
      deep: "Strategy is a strong interview choice. Singleton is controversial: mention it, but defend testability with injectable dependencies.",
      concepts: [["Strategy", "Eviction algorithm boundary."], ["Singleton", "One process-wide manager."], ["Testability", "Fake policy and clock."], ["Lifecycle", "Manager starts/stops daemon." ]],
      examples: [["LRU", "Least recently used."], ["LFU", "Least frequently used."], ["Manager", "Wires cache and sweeper." ]],
      flow: ["Define policy", "Implement LRU", "Inject policy", "Manager wires dependencies", "Tests swap fakes"],
      tradeoffs: [["Strategy", "Extensible with small interface cost."], ["Singleton", "Easy access but hidden global state."], ["DI", "Cleaner serious-code default." ]],
      failures: ["Static global cache everywhere.", "Policy mutating storage internals too much.", "No shutdown path."],
      useWhen: ["Eviction algorithm can change."],
      avoidWhen: ["Do not force Singleton if normal construction works."],
      code: "interface EvictionPolicy<K> {\n    void onGet(K key);\n    void onPut(K key);\n    Optional<K> evictCandidate();\n}",
      questions: [["EASY", "Why Strategy?", "LRU, LFU, FIFO vary independently from storage."], ["MEDIUM", "Singleton risk?", "Hidden global state and harder tests."], ["HARD", "How defend Singleton?", "Only as thin process-wide manager with injectable internals." ]],
      revision: "Strategy is core; Singleton is optional."
    }),
    day(23, "core-storage", "Core Storage with ConcurrentHashMap", {
      problem: "Redis-Lite needs O(1) lookup and thread-safe access. HashMap is unsafe under concurrent mutation.",
      mental: "ConcurrentHashMap is the storage index; eviction metadata is separate.",
      core: "Use ConcurrentHashMap<K, CacheEntry<V>> for storage. Compound operations still may need external locking.",
      deep: "Store immutable or controlled CacheEntry objects. Prefer replacing entries over mutating fields where possible.",
      concepts: [["O(1)", "Expected constant key lookup."], ["Safe map ops", "CHM handles concurrent get/put/remove."], ["CacheEntry", "Value plus expiry metadata."], ["Compound invariant", "Map and eviction policy must agree." ]],
      examples: [["put", "Create entry and insert."], ["get", "Check expiry and return."], ["delete", "Remove map and policy." ]],
      flow: ["Build entry", "Acquire needed coordination", "Put in CHM", "Update policy", "Evict if needed"],
      tradeoffs: [["CHM", "Fast concurrent access."], ["Extra lock", "Needed for map+list consistency."], ["Immutable entry", "Less mutation risk." ]],
      failures: ["Using HashMap.", "Updating policy after map without plan.", "Returning expired value."],
      useWhen: ["Core key-value storage."],
      avoidWhen: ["Need ordered traversal as primary operation."],
      code: "record CacheEntry<V>(V value, long expiresAtMillis) {\n    boolean expired(long now) { return expiresAtMillis > 0 && now >= expiresAtMillis; }\n}\nConcurrentHashMap<String, CacheEntry<String>> store = new ConcurrentHashMap<>();",
      questions: [["EASY", "Why CHM?", "Thread-safe expected O(1) lookup/update."], ["MEDIUM", "What does entry contain?", "Value plus expiry metadata."], ["HARD", "Why not whole solution?", "Capacity and LRU metadata span multiple structures." ]],
      revision: "ConcurrentHashMap is storage, not full correctness."
    }),    day(24, "ttl-model", "CacheEntry and TTL Model", {
      problem: "TTL logic scattered across get, put, and daemon code becomes inconsistent.",
      mental: "A cache entry is value plus deadline. A Clock abstraction tells whether the deadline passed.",
      core: "Store expiresAtMillis or Instant per entry. Check expiry on get and sweep expired entries in background.",
      deep: "Lazy expiry prevents stale returns but leaves cold expired keys. Active sweep reclaims memory but can pause if too large. Use both.",
      concepts: [["TTL", "How long key stays valid."], ["expiresAt", "Absolute deadline."], ["Lazy expiry", "Remove when read."], ["Active sweep", "Background cleanup." ]],
      examples: [["Session", "30 minute TTL."], ["Feature flag", "May never expire."], ["Cold key", "Needs daemon sweep." ]],
      flow: ["put receives ttl", "Compute expiresAt", "Store entry", "get checks expiry", "daemon removes expired"],
      tradeoffs: [["Lazy only", "Simple but leaks cold expired keys."], ["Sweep only", "May return stale between sweeps."], ["Both", "Correct reads plus cleanup." ]],
      failures: ["Using system time everywhere.", "Confusing duration with deadline.", "Unsafe removal while iterating."],
      useWhen: ["Temporary keys."],
      avoidWhen: ["Durable data requirements."],
      code: "interface Clock { long nowMillis(); }\nlong expiresAt(Duration ttl, Clock clock) {\n    return ttl.isZero() ? 0 : clock.nowMillis() + ttl.toMillis();\n}",
      questions: [["EASY", "What is TTL?", "Time-to-live for a key."], ["MEDIUM", "Why absolute expiresAt?", "Reads compare now to one deadline."], ["HARD", "Why lazy plus active expiry?", "Lazy prevents stale reads; active removes cold expired keys." ]],
      revision: "TTL = deadline per entry plus lazy check plus active sweep."
    }),
    day(25, "lru-lfu-list", "LRU/LFU and Thread-Safe Doubly Linked List", {
      problem: "LRU requires reordering nodes on access, so get mutates recency metadata.",
      mental: "Map finds the node in O(1). Doubly linked list maintains order. Moving node changes several pointers atomically.",
      core: "Implement LRU with map plus doubly linked list. Protect list mutations with a write lock or policy lock.",
      deep: "LFU needs frequency buckets and tie-breaking, more complex than LRU. Implement LRU first; make LFU another Strategy.",
      concepts: [["LRU", "Evict least recently used."], ["LFU", "Evict least frequently used."], ["Doubly linked list", "O(1) detach/move."], ["Policy lock", "Protect pointer updates." ]],
      examples: [["get", "Return value and move node to head."], ["put", "Add head and evict tail."], ["LFU", "Lowest frequency, oldest tie." ]],
      flow: ["Map lookup", "Acquire policy lock", "Detach node", "Attach at head", "Evict tail if needed", "Update map"],
      tradeoffs: [["Exact LRU", "Correct but every get writes."], ["Approx LRU", "Higher throughput but less exact."], ["LFU", "Better frequency signal, more metadata." ]],
      failures: ["Moving nodes under read lock.", "Forgetting prev/next updates.", "Map/list disagreement."],
      useWhen: ["Capacity-bounded cache."],
      avoidWhen: ["Very high read throughput where exact recency is too costly."],
      code: "final class Node<K> { K key; Node<K> prev; Node<K> next; }\nvoid moveToHead(Node<K> node) { detach(node); attachAfterHead(node); }",
      questions: [["EASY", "Why doubly linked list?", "O(1) remove and move-to-head when node is known."], ["MEDIUM", "Why is get a write in LRU?", "It updates recency order."], ["HARD", "How keep map/list consistent?", "Update both under one policy/write lock." ]],
      revision: "LRU = map lookup plus locked list reorder."
    }),
    day(26, "read-write-lock", "ReadWriteLock Concurrency Control", {
      problem: "The cache should allow many reads, but evictions and overwrites must not corrupt shared state.",
      mental: "Read lock is shared. Write lock is exclusive. Any metadata mutation needs write safety.",
      core: "Use ReadWriteLock around storage/policy invariants. Exact LRU get may require write lock because it mutates order.",
      deep: "Java ReentrantReadWriteLock does not support safe direct upgrade from read to write. Design get paths carefully: read-only get can use read lock; exact LRU touch should use write lock or approximate recency.",
      concepts: [["Read lock", "Many readers."], ["Write lock", "Exclusive mutation."], ["Upgrade trap", "Read-to-write can deadlock/starve."], ["Invariant", "Map, size, policy agree." ]],
      examples: [["get no touch", "Read lock."], ["exact LRU get", "Write lock for move-to-head."], ["put/evict", "Write lock." ]],
      flow: ["Classify operation", "Acquire lock", "Check expiry/capacity", "Mutate if needed", "Unlock in finally"],
      tradeoffs: [["Read throughput", "High when reads are true reads."], ["Exact LRU", "Less read parallelism."], ["Approx policy", "Better throughput, less precision." ]],
      failures: ["Unsafe lock upgrade.", "External listener inside write lock.", "Returning mutable Entry."],
      useWhen: ["Read-heavy workload with occasional writes."],
      avoidWhen: ["Every operation writes heavily."],
      code: "rw.writeLock().lock();\ntry {\n    store.put(key, entry);\n    evictionPolicy.onPut(key);\n    evictIfNeeded();\n} finally { rw.writeLock().unlock(); }",
      questions: [["EASY", "What does write lock protect?", "Exclusive mutations to shared invariants."], ["MEDIUM", "Why can LRU reduce read parallelism?", "get updates recency metadata."], ["HARD", "What is upgrade risk?", "Holding read lock while waiting for write lock can deadlock/starve." ]],
      revision: "ReadWriteLock helps only when reads are mostly read-only."
    }),
    day(27, "ttl-daemon", "TTL Daemon with ScheduledExecutorService", {
      problem: "Expired keys nobody reads can sit forever and waste memory.",
      mental: "The TTL daemon is a janitor: wake, sweep bounded work, sleep, shut down cleanly.",
      core: "Use ScheduledExecutorService with fixed delay. Sweep expired keys safely, bound each sweep, name the thread, and stop it on close.",
      deep: "A full scan under one long write lock can hurt latency. Interview version can full-scan with caveat; production can use priority queue, timing wheel, or incremental sweep.",
      concepts: [["ScheduledExecutorService", "Runs periodic tasks."], ["Daemon", "Background cleanup service."], ["Fixed delay", "Waits after previous run finishes."], ["Bounded sweep", "Avoids long pauses." ]],
      examples: [["Every second", "Remove expired sessions."], ["Incremental", "Scan at most N keys."], ["Shutdown", "close stops scheduler." ]],
      flow: ["Create scheduler", "Schedule sweep", "Check expiry", "Remove safely", "Shutdown on close"],
      tradeoffs: [["Full scan", "Simple, may pause."], ["Priority queue", "Efficient expiry order, more metadata."], ["Timing wheel", "Scales, more complex." ]],
      failures: ["Forgetting shutdown.", "Daemon mutates without locks.", "Long sweep blocks user ops."],
      useWhen: ["TTL cache with cold expired keys."],
      avoidWhen: ["Tiny first iteration where lazy expiry is enough."],
      code: "ScheduledExecutorService sweeper = Executors.newSingleThreadScheduledExecutor();\nsweeper.scheduleWithFixedDelay(this::sweepExpiredKeys, 1, 1, TimeUnit.SECONDS);",
      questions: [["EASY", "Why TTL daemon?", "To remove expired keys nobody reads."], ["MEDIUM", "fixedRate vs fixedDelay?", "fixedDelay waits after a run completes."], ["HARD", "How avoid sweep latency spikes?", "Bound work, avoid long write locks, or use expiry-ordered metadata." ]],
      revision: "TTL daemon prevents memory leaks but must not become the latency problem."
    }),
    day(28, "api-operations", "Redis-Lite API Operations", {
      problem: "A design is incomplete unless each public method defines expiry, capacity, concurrency, and return semantics.",
      mental: "Every API method should say lock type, map action, policy action, expiry behavior, and return value.",
      core: "Define get, put, delete, expire, ttl, containsKey, and size. Use Optional for missing values and boolean for delete/expire success.",
      deep: "get must not return expired entries. put updates entry and policy. delete removes from map and policy. expire changes deadline. size must define whether it counts expired-but-not-swept entries.",
      concepts: [["get", "Optional.empty for missing/expired."], ["put", "Insert/overwrite and evict."], ["delete", "Remove map and policy."], ["expire/ttl", "Update/read expiry metadata." ]],
      examples: [["GET missing", "Optional.empty."], ["PUT full", "Evict candidate."], ["EXPIRE", "false when key missing." ]],
      flow: ["Validate", "Acquire lock", "Check expiry", "Map mutation", "Policy update", "Return result"],
      tradeoffs: [["Optional", "Clear absence."], ["Boolean", "Simple success signal."], ["Exception", "Invalid argument, not normal miss." ]],
      failures: ["Returning null.", "Deleting map but not LRU list.", "Undefined size semantics."],
      useWhen: ["Finalizing public cache contract."],
      avoidWhen: ["Do not copy all Redis commands before core correctness."],
      code: "Optional<V> get(K key) {\n    CacheEntry<V> entry = store.get(key);\n    if (entry == null || entry.expired(clock.nowMillis())) return Optional.empty();\n    evictionPolicy.onGet(key);\n    return Optional.of(entry.value());\n}",
      questions: [["EASY", "What should missing get return?", "Optional.empty."], ["MEDIUM", "What must delete update?", "Storage map and eviction metadata."], ["HARD", "Why define size semantics?", "Expired keys may exist until sweep; callers need clear meaning." ]],
      revision: "Every API method needs locking, expiry, policy, and return semantics."
    }),
    day(29, "testing-races", "Testing Races and Latency", {
      problem: "Concurrent code can pass single-thread tests and still fail under interleavings.",
      mental: "Test the invariant, not only the example: capacity holds, expired keys disappear, map/list remain consistent.",
      core: "Use FakeClock for TTL, CountDownLatch/CyclicBarrier for stress starts, and repeated invariant tests for concurrency confidence.",
      deep: "Concurrency tests are often probabilistic. Use barriers to force simultaneous starts, repeat tests, and keep core logic small enough for deterministic tests. Consider JCStress for memory-model micro-tests.",
      concepts: [["FakeClock", "Deterministic TTL."], ["CountDownLatch", "Start/wait for workers."], ["Invariant", "Capacity, no stale reads, map/list agreement."], ["Latency", "Measure sweep and lock duration." ]],
      examples: [["Concurrent put", "100 threads, capacity 10, size <= 10."], ["TTL", "Advance fake time."], ["Race", "get/put/delete should not corrupt list." ]],
      flow: ["Arrange cache", "Synchronize start", "Run workers", "Wait", "Assert invariants", "Repeat"],
      tradeoffs: [["Unit tests", "Deterministic."], ["Stress tests", "Find timing bugs but can be flaky."], ["JCStress", "Best for JMM micro-tests, heavier." ]],
      failures: ["Only happy path tests.", "Thread.sleep for TTL.", "No internal consistency assertion."],
      useWhen: ["Before claiming thread safety."],
      avoidWhen: ["Do not rely only on manual demos."],
      code: "CountDownLatch start = new CountDownLatch(1);\nCountDownLatch done = new CountDownLatch(workers);\n// submit workers, then start.countDown(), done.await(), assert cache.size() <= capacity",
      questions: [["EASY", "Why FakeClock?", "TTL tests without sleeping."], ["MEDIUM", "Capacity invariant?", "Size never exceeds configured capacity."], ["HARD", "Why are concurrency tests hard?", "Bugs depend on timing and interleavings." ]],
      revision: "Thread-safe design needs invariant and stress testing."
    }),
    day(30, "final-walkthrough", "Final Interview Walkthrough", {
      problem: "The final answer must connect requirements, classes, concurrency, eviction, TTL, APIs, tests, and trade-offs in one story.",
      mental: "Walk one request path at a time, then defend invariants and extensions.",
      core: "Start with scope, draw components, code core methods, explain locks, then discuss LFU, persistence, sharding, metrics, virtual threads, and approximate eviction.",
      deep: "Do not start with distributed Redis. Nail one JVM in-memory store first. When asked production follow-up, separate interview implementation from production upgrades.",
      concepts: [["Structure", "Requirements -> classes -> flows -> code -> concurrency -> tests."], ["Classes", "CacheService, CacheEntry, EvictionPolicy, LruPolicy, TtlSweeper, Clock."], ["Invariants", "Capacity, expiry, map/list agreement."], ["Extensions", "LFU, persistence, metrics, sharding." ]],
      examples: [["get flow", "Read, expiry check, policy update, Optional."], ["put flow", "Write, policy, evict."], ["sweep flow", "Daemon removes expired safely." ]],
      flow: ["Clarify scope", "List classes", "Explain get/put/delete", "Explain locks", "Show LRU/TTL", "Name tests/extensions"],
      tradeoffs: [["Exact LRU", "Correct but get mutates."], ["Approx LRU", "Faster but less precise."], ["Single JVM", "Great LLD scope; distributed Redis is another layer." ]],
      failures: ["Jumping to networking first.", "No lock story.", "No tests or shutdown."],
      useWhen: ["Mock interview day."],
      avoidWhen: ["Do not overstuff first 10 minutes with every extension."],
      code: "final class RedisLite<K,V> implements Cache<K,V> {\n    private final ConcurrentHashMap<K, CacheEntry<V>> store;\n    private final EvictionPolicy<K> policy;\n    private final ReadWriteLock lock = new ReentrantReadWriteLock();\n    private final ScheduledExecutorService sweeper;\n}",
      questions: [["EASY", "Main components?", "Cache API, CHM storage, CacheEntry, EvictionPolicy, lock, TTL sweeper, Clock."], ["MEDIUM", "Key invariants?", "Capacity limit, no stale returns, storage/policy consistency."], ["HARD", "Production follow-ups?", "Persistence, sharding, protocol layer, metrics, approximate eviction, distributed locking." ]],
      revision: "Final answer = scoped product plus correct concurrent implementation story."
    })
  ]);

  window.LLD_SYLLABUS.push(phase1, phase2, phase3, phase4);
  window.LLD_REFERENCE.push({
    title: "Redis-Lite Concurrency Checklist",
    rows: [
      ["Storage", "ConcurrentHashMap gives O(1) thread-safe key lookup."],
      ["Eviction", "Strategy pattern: LRU first, LFU as extension."],
      ["Metadata", "Map plus LRU list needs one consistency boundary."],
      ["TTL", "Lazy check on get plus ScheduledExecutorService sweep."],
      ["Locks", "ReadWriteLock only helps when reads do not mutate metadata."],
      ["Tests", "FakeClock, CountDownLatch stress, capacity and expiry invariants."]
    ]
  });
})();